
import React from 'react';
import { SectionId } from '../types';

const EngineeringCraft = () => {
  const crafts = [
    {
      title: 'Modular Design Patterns',
      desc: 'Our compiler generates atomic, reusable React components following industry-best practices for maintainability.'
    },
    {
      title: 'Performance Optimization',
      desc: 'Automatic code-splitting, tree-shaking, and asset optimization ensure lighthouse scores of 95+ out of the box.'
    },
    {
      title: 'Type-Safe Intelligence',
      desc: 'Deep integration with TypeScript ensures that every generated function and component is fully typed and robust.'
    }
  ];

  return (
    <section id={SectionId.Craftsmanship} className="py-32 bg-google-bg text-google-text border-t border-google-border">
      <div className="max-w-7xl mx-auto px-6">
        <div className="flex flex-col lg:flex-row gap-20 items-center">
          <div className="lg:w-1/2">
            <span className="text-google-accent text-[11px] font-black uppercase tracking-[0.4em] mb-4 block">The Engineering Core</span>
            <h2 className="text-4xl md:text-5xl font-black italic tracking-tighter mb-8 leading-tight text-white uppercase">Meticulous Logic: <br/>Every Line With Intent</h2>
            <p className="text-google-textMuted text-lg font-light mb-12 leading-relaxed max-w-xl">
              From modular architectural patterns to precise type definitions, every line of code generated by moda AI is a fusion of AI intelligence and senior-level engineering standards.
            </p>
            <div className="space-y-12">
              {crafts.map((item, idx) => (
                <div key={idx} className="flex gap-8 group">
                  <span className="text-google-accent font-mono text-4xl font-black opacity-20 group-hover:opacity-100 transition-opacity">0{idx + 1}</span>
                  <div>
                    <h3 className="font-black text-white text-base uppercase tracking-widest mb-2 group-hover:text-google-success transition-colors">{item.title}</h3>
                    <p className="text-google-textMuted font-light leading-relaxed text-sm">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
          <div className="lg:w-1/2 grid grid-cols-2 gap-6 relative">
             <div className="absolute inset-0 bg-google-accent/5 blur-[120px] rounded-full z-0"></div>
             <div className="relative z-10 overflow-hidden rounded-[2.5rem] border border-google-border shadow-2xl group">
               <img 
                src="https://images.unsplash.com/photo-1542831371-29b0f74f9713?q=80&w=2070&auto=format&fit=crop" 
                className="w-full aspect-square object-cover grayscale group-hover:grayscale-0 transition-all duration-1000" 
                alt="Code Matrix"
               />
               <div className="absolute inset-0 bg-google-bg/40 group-hover:bg-transparent transition-colors"></div>
             </div>
             <div className="relative z-10 overflow-hidden rounded-[2.5rem] border border-google-border shadow-2xl mt-16 group">
               <img 
                src="https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2070&auto=format&fit=crop" 
                className="w-full aspect-square object-cover grayscale group-hover:grayscale-0 transition-all duration-1000" 
                alt="Cybersecurity"
               />
             </div>
             <div className="relative z-10 overflow-hidden rounded-[2.5rem] border border-google-border shadow-2xl -mt-16 group">
               <img 
                src="https://images.unsplash.com/photo-1587620962725-abab7fe55159?q=80&w=2031&auto=format&fit=crop" 
                className="w-full aspect-square object-cover grayscale group-hover:grayscale-0 transition-all duration-1000" 
                alt="Developer Setup"
               />
             </div>
             <div className="relative z-10 overflow-hidden rounded-[2.5rem] border border-google-border shadow-2xl group">
               <img 
                src="https://images.unsplash.com/photo-1531297484001-80022131f5a1?q=80&w=2020&auto=crop" 
                className="w-full aspect-square object-cover grayscale group-hover:grayscale-0 transition-all duration-1000" 
                alt="Advanced Tech"
               />
             </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default EngineeringCraft;
