
import React from 'react';
import { SectionId } from '../types';

const EngineeringCraft = () => {
  const crafts = [
    {
      title: 'Modular Design Patterns',
      desc: 'Our compiler generates atomic, reusable React components following industry-best practices for maintainability.'
    },
    {
      title: 'Performance Optimization',
      desc: 'Automatic code-splitting, tree-shaking, and asset optimization ensure lighthouse scores of 95+ out of the box.'
    },
    {
      title: 'Type-Safe Intelligence',
      desc: 'Deep integration with TypeScript ensures that every generated function and component is fully typed and robust.'
    }
  ];

  return (
    <section id={SectionId.Craftsmanship} className="py-32 bg-white text-aurae-primary">
      <div className="max-w-7xl mx-auto px-6">
        <div className="flex flex-col lg:flex-row gap-16 items-center">
          <div className="lg:w-1/2">
            <span className="text-aurae-accent text-[10px] uppercase tracking-[0.4em] font-bold mb-4 block">The Engineering Core</span>
            <h2 className="text-4xl md:text-5xl font-extrabold tracking-tighter mb-6 leading-tight">Meticulous Logic: <br/>Every Line With Intent</h2>
            <p className="text-aurae-muted text-lg font-light mb-12 leading-relaxed">
              From modular architectural patterns to precise type definitions, every line of code generated by Auraé Vision is a fusion of AI intelligence and senior-level engineering standards.
            </p>
            <div className="space-y-12">
              {crafts.map((item, idx) => (
                <div key={idx} className="flex gap-6 group">
                  <span className="text-aurae-accent font-mono text-3xl font-extrabold opacity-20 group-hover:opacity-100 transition-opacity">0{idx + 1}</span>
                  <div>
                    <h3 className="font-sans font-bold text-sm uppercase tracking-widest mb-2">{item.title}</h3>
                    <p className="text-aurae-muted font-light leading-relaxed text-sm">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
          <div className="lg:w-1/2 grid grid-cols-2 gap-4">
             <div className="relative overflow-hidden rounded-2xl shadow-2xl group">
               <img 
                src="https://images.unsplash.com/photo-1542831371-29b0f74f9713?q=80&w=2070&auto=format&fit=crop" 
                className="w-full aspect-square object-cover grayscale group-hover:grayscale-0 transition-all duration-700" 
                alt="Code Matrix"
               />
               <div className="absolute inset-0 bg-aurae-accent/10 group-hover:bg-transparent transition-colors"></div>
             </div>
             <div className="relative overflow-hidden rounded-2xl shadow-2xl mt-12 group">
               <img 
                src="https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=2070&auto=format&fit=crop" 
                className="w-full aspect-square object-cover grayscale group-hover:grayscale-0 transition-all duration-700" 
                alt="Cybersecurity"
               />
             </div>
             <div className="relative overflow-hidden rounded-2xl shadow-2xl -mt-12 group">
               <img 
                src="https://images.unsplash.com/photo-1587620962725-abab7fe55159?q=80&w=2031&auto=format&fit=crop" 
                className="w-full aspect-square object-cover grayscale group-hover:grayscale-0 transition-all duration-700" 
                alt="Developer Setup"
               />
             </div>
             <div className="relative overflow-hidden rounded-2xl shadow-2xl group">
               <img 
                src="https://images.unsplash.com/photo-1531297484001-80022131f5a1?q=80&w=2020&auto=crop" 
                className="w-full aspect-square object-cover grayscale group-hover:grayscale-0 transition-all duration-700" 
                alt="Advanced Tech"
               />
             </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default EngineeringCraft;
